name: 'setup-terraform tests'

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  terraform-versions:
    name: 'Terraform Versions'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terraform-versions: [0.11.14, latest]
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Terraform - ${{ matrix['terraform-versions'] }}
      uses: ./
      with:
        terraform_version: ${{ matrix['terraform-versions'] }}

    - name: Validate Teraform Version - ${{ matrix['terraform-versions'] }}
      if: ${{ matrix['terraform-versions'] != 'latest' }}
      run: terraform version | grep ${{ matrix['terraform-versions']}}

    - name: Validate Teraform Version - ${{ matrix['terraform-versions'] }}
      if: ${{ matrix['terraform-versions'] == 'latest' }}
      run: terraform version | grep 'Terraform v'